### PR TITLE
fix comparison bug in editContainer

### LINKED ISSUE #1260: bug when selecting container image in editContainer ui plugin. when clicking on newly created image, the "select image..." text comes up instead of the image name

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
delete id to make comparison work correctly
## Issues related to this change
closes #1260

### CODE REVIEW

File: web/packages/plugins/ui/job-handlers/src/EditContainer.tsx [hunk 1]
```diff
@@ -89,15 +90,17 @@ export const EditContainer = (props: DmtUIPlugin) => {
 
             <Select
               style={{ width: PATH_INPUT_FIELD_WIDTH }}
-              onChange={(e: ChangeEvent<HTMLSelectElement>) =>
+              onChange={(e: ChangeEvent<HTMLSelectElement>) => {
+                console.log('parse res', JSON.parse(e.target.value))
```
Comment (soofstad) [inline web/packages/plugins/ui/job-handlers/src/EditContainer.tsx:94]:
```suggestion
```

File: web/packages/plugins/ui/job-handlers/src/EditContainer.tsx [hunk 2]
```diff
@@ -89,15 +90,17 @@ export const EditContainer = (props: DmtUIPlugin) => {
...
                 setFormData({ ...formData, image: JSON.parse(e.target.value) })
-              }
+              }}
               value={getImageStoredInFormData(containerImages, formData)}
             >
               <option value={''} selected disabled hidden>
                 Choose image...
               </option>
               {containerImages.map((image: TContainerImage, index: number) => {
+                console.log('image as jsonstrign', JSON.stringify(image))
```
Comment (soofstad) [inline web/packages/plugins/ui/job-handlers/src/EditContainer.tsx:103]:
```suggestion
```

**Review by soofstad — APPROVED** [review]
