### PR TITLE
fix invalid date bug

### LINKED ISSUE #1376: fix(analysis-platform): invalided date not working as aspected

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
bugfix: do not show "invalid date" in the job table. use the job object directly without the local started state.
## Why is this pull request needed?
bugfix
## Issues related to this change

closes #1376

### CODE REVIEW

File: web/packages/plugins/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx [hunk 1]
```diff
@@ -132,11 +130,7 @@ const JobRow = (props: {
   return (
     <Table.Row>
       <Table.Cell onClick={viewJob}>
-        {jobStatus !== EJobStatus.CREATED
-          ? job.started
-            ? new Date(job.started).toLocaleString(navigator.language)
-            : started
-          : 'Not started'}
+        {jobStatus !== EJobStatus.CREATED ? job.started : 'Not started'}
```
Comment (eoaksnes) [inline web/packages/plugins/analysis-platform/src/modules/Analysis/components/AnalysisJobTable.tsx:133]: Should this code be added? `new Date(job.started).toLocaleString(navigator.language)

**Review by eoaksnes — CHANGES_REQUESTED** [review]

**Review by netr0m — APPROVED** [review]
