### PR TITLE
Use Axios for openapi generator

### LINKED ISSUE #1055: Change openapi generator
- [ ] Find out what is working and not working
- [ ] Replace native with Axios TS generator

### PR DESCRIPTION
**Pull request by netr0m**
## What does this pull request change?
- [x] Re-adds the [previously deleted](https://github.com/equinor/data-modelling-tool/commit/9bb0396c1785a901f49d1f53f19b4e377e1f3bb2#diff-938ebc696fa2bfa57d66128e5f4a3af96e085cf4b5dece9ae05f2b696c23d6c5) `generate-api.sh` script
- [x] Change the openapi-generator-cli script to use the `typescript-axios` generator (previously used `typescript-fetch`)
- [x] Remove the "generated API wrapper"
- [x] Implement class
  - [x] Extending the `DefaultApi` from the generated code
- [x] Remove the previously generated `typescript-fetch` files
- [x] Test to ensure all calls work as expected

## Why is this pull request needed?
To switch to Axios bindings for the generated API client for the frontend (DMT)

## Issues related to this change:
- Resolves #1055
- (PR) equinor/data-modelling-storage-service/pull/203

## Checklist

- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added types and interfaces where possible
- [ ] You have added tests
- [ ] You have updated documentation
- [ ] You use defined architecture principles and project structures
- [ ] You are happy with the code quality

### CODE REVIEW

File: web/packages/plugins/shared/common/src/hooks/useBlueprint.tsx [hunk 1]
```diff
@@ -12,9 +12,9 @@ export const useBlueprint = (typeRef: string) => {
   useEffect(() => {
     setLoading(true)
     dmssAPI
-      .getBlueprint({ typeRef: typeRef })
-      .then((document) => {
-        setBlueprint(document)
+      .blueprintGet({ typeRef: typeRef })
+      .then((response: any) => {
+        setBlueprint(response)
```
Comment (soofstad) [inline web/packages/plugins/shared/common/src/hooks/useBlueprint.tsx:17]: should this not be "response.data"?

**Review by soofstad — APPROVED** [review]
