### PR TITLE
Minor fixes

### LINKED ISSUE #1301: change order of workflow and workflow task in the applicationinput ui plugin?

### LINKED ISSUE #1302: add an indicator for unsaved changes next to the save button in the ui plugins?

### LINKED ISSUE #1304: Adding a package in DMT does not shows up in analysis platform without refresh

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
* add indicator for unsaved changes
* Add a function to TreeNode to update content of a datasource node - required to be able to display newly created root 
packages at once
* change order of workflow and workflow task input fields 
## Issues related to this change
closes #1302 
closes #1304 
closes #1301

### CODE REVIEW

File: web/packages/plugins/shared/common/src/domain/Tree.tsx [hunk 1]
```diff
@@ -159,6 +159,72 @@ export class TreeNode {
...
+        // If the search fail, set the DataSource as an error node.
+        console.error(error)
+        this.tree.index[this.dataSource].type = 'error'
+        this.tree.index[this.dataSource].message = error.message
+      })
+      .finally(() => {
+        this.tree.updateCallback(this.tree)
+      })
+  }
+
```
Comment (soofstad) [inline web/packages/plugins/shared/common/src/domain/Tree.tsx:227]: Instead of having this as a separate/different method than the one on other folders, can it be added to node.expand(), just for dataSources.

Also, this is very similar to what is happening in Tree.init(). Could you try and not duplicate this, but rather use the same code in both places?

**Review by soofstad — CHANGES_REQUESTED** [review]

**Review by soofstad — APPROVED** [review]
Good! :slightly_smiling_face:
